--sentence
CREATE TABLE IF NOT EXISTS CAMPAIGN
(
 _ID INT NOT NULL,
 POP_UP Text NOT NULL,
 BACKGROUND Text NOT NULL,
 LOCK_SCREEN Text NOT NULL,
 LOADED_DATE Text NOT NULL,
 STATUS INT NOT NULL, 
 LINK Text NOT NULL,
 PRIMARY KEY (_ID)
)

--sentence
CREATE TABLE IF NOT EXISTS STATICS
(
  _ID INT NOT NULL,
  CAMPAIGN_ID INT NOT NULL,
  ACTION_ID INT NOT NULL,
  TYPE_ID INT NOT NULL,
  PRIMARY KEY (_ID)
)


