--sentence
CREATE TABLE IF NOT EXISTS CAMPAIGN
(
 _ID INT NOT NULL,
 POP_UP Text NOT NULL,
 BACKGROUND Text NOT NULL,
 LOCK_SCREEN Text NOT NULL,
 LOADED_DATE Text NOT NULL,
 WATCHED INT NOT NULL, 
 PRIMARY KEY (_ID)
)


